name: Deploy to Heroku

on:
  push:
    branches:
      - main  # デプロイしたいブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2' # プロジェクトのRubyバージョンに合わせてください

    - name: Install dependencies
      run: bundle install

    - name: Display Git Remote Information
      run: git remote -v

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.11.10 # Herokuデプロイ用のGitHub Actions
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        usedocker: false # Dockerを使用する場合はtrueに設定
        branch: main # デプロイするブランチ
        dontuseforce: true # 強制プッシュを避けるためにtrueに設定
